spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      username: roczyno
      password: roczyno
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  mail:
    host: localhost
    port: 1025
    username: adiabajacob9@gmail.com
    password: dsjksjfjs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 0
