spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://task_ms_config-server:8888
server:
  port: 0

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: notification_ms.log
