version: '3.8'

services:
  zipkin:
    container_name: task_manager_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - task_manager_microservice_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_manager_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      task_manager_microservice_net:

  mongoDB:
    container_name: task_manager_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: roczyno
      MONGO_INITDB_ROOT_PASSWORD: roczyno
    networks:
      task_manager_microservice_net:


  mongo_express:
    container_name: task_manager_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_MONGODB_ADMINUSERNAME: roczyno
      ME_CONFIG_MONGODB_ADMINPASSWORD: roczyno
    networks:
      task_manager_microservice_net:

  mail_dev:
    container_name: task_manager_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      task_manager_microservice_net:






networks:
  task_manager_microservice_net:
    driver: bridge

volumes:
  mongo:
