version: '3.8'

services:
  zipkin:
    container_name: task_manager_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - task_manager_microservice_net



networks:
  task_manager_microservice_net:
    driver: bridge
