version: '3.8'

services:
  zipkin:
    container_name: task_manager_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - task_manager_microservice_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_manager_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      task_manager_microservice_net:

  mongoDB:
    container_name: task_manager_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: roczyno
      MONGO_INITDB_ROOT_PASSWORD: roczyno
    networks:
      task_manager_microservice_net:

  mongo_express:
    container_name: task_manager_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_MONGODB_ADMINUSERNAME: roczyno
      ME_CONFIG_MONGODB_ADMINPASSWORD: roczyno
    networks:
      task_manager_microservice_net:

  mail_dev:
    container_name: task_manager_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      task_manager_microservice_net:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: task_manager_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - task_manager_microservice_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: task_manager_logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - "C:/Users/JacobSabbathAdiaba/OneDrive - AmaliTech gGmbH/Desktop/PP/Java/microservices/java-task-manager-microservice:/logs"
    networks:
      - task_manager_microservice_net
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: task_manager_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - task_manager_microservice_net
    depends_on:
      - elasticsearch


networks:
  task_manager_microservice_net:
    driver: bridge

volumes:
  mongo:
  es_data:
