server:
  port: 5001

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/

eureka.client.service-url.default-zone=
