
server:
  port: 8083

spring:
  application:
    name: submission-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: logs/sub_ms.log


