
server:
  port: 8083

spring:
  application:
    name: submission-service
  config:
    import: optional:configserver:http://localhost:8888


user-service:
  url: http://localhost:8085

task-service:
  url: http://localhost:8082

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: sub_ms.log


