
server:
  port: 8083

spring:
  application:
    name: submission-service
  config:
    import: optional:configserver:http://task_ms_config-server:8888


user-service:
  url: http://task_ms_user-service:8085

task-service:
  url: http://task_ms_task-service:8082

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: sub_ms.log


