server:
  port: 8085

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://task_ms_config-server:8888


#logging:
#  pattern:
#    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
#  file:
#    name: logs/user_ms.log
