server:
  port: 8085

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888





#  file:
#    name: logs/user_ms.log
management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"


