server:
  port: 8082

spring:
  application:
    name: task-service
  config:
    import: optional:configserver:http://task_ms_config-server:8888

    #rabbit mq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

user-service:
  url: http://task_ms_user-service:8085

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: task_ms.log

#rabbitMq
