server:
  port: 8082

spring:
  application:
    name: task-service
  config:
    import: optional:configserver:http://localhost:8888

    #rabbit mq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: logs/task_ms.log

#rabbitMq
