server:
  port: 8082
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    generate-ddl: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
  application:
    name: task-service
  datasource:
    password: roczyno
    username: postgres
    url: jdbc:postgresql://localhost:5432/task_service_db
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/



  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke # Use an environment variable for security
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true