eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/

spring:
  cloud:
    config:
      override.system-properties: false

  zipkin:
    base-url: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1

logging:
  level:
    root: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"


