spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    generate-ddl: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect

  datasource:
    password: roczyno
    username: postgres
    url: jdbc:postgresql://localhost:5432/taskms_task_db
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true


  tracing:
    sampling:
      probability: 1

resilience4j:
  circuitbreaker:
    instances:
      userBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based



