spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    generate-ddl: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect

  datasource:
    password: roczyno
    username: postgres
    url: jdbc:postgresql://localhost:5432/task_service_db
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


