spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    generate-ddl: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect

  datasource:
    password: roczyno
    username: postgres
    url: jdbc:postgresql://localhost:5432/taskms_task_db
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true


  tracing:
    sampling:
      probability: 1

resilience4j:
  circuitbreaker:
    instances:
      userBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - feign.FeignException



